version: "3.9"

services:
  python-service:
    build: ./python-service
    container_name: python-service
    ports:
      - "5000:5000"

  node-service:
    build: ./node-service
    container_name: node-service
    ports:
      - "3000:3000"
    environment:
      PYTHON_URL: http://python-service:5000
    depends_on:
      - python-service
